# pubspec.yaml
name: realityquest
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  image_picker: ^1.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^17.2.3
  permission_handler: ^11.3.1
  timezone: ^0.9.4
  audioplayers: ^6.1.0
  wakelock_plus: ^1.2.8

# ðŸ”¥ TAMBAH DI BAWAH INI:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  analyzer: ^6.4.1
  flutter_launcher_icons: ^0.13.1  # âœ… LINE INI
  
flutter:
  uses-material-design: true
  
  # Assets (pastikan ada ini)
  assets:
    - assets/icon/